### ISSUE TITLE
Inline Support is not working

### ISSUE THREAD

**Issue by CentralLinks17** [VJBots/VJ-FILTER-BOT#124]
please change the inline.py code to latest modification

2024-11-16T09:07:50.532626+00:00 app[web.1]: 09:07:50 AM - 376 - pyrogram.dispatcher - dispatcher - ERROR - 'file_type'
2024-11-16T09:07:50.532635+00:00 app[web.1]: Traceback (most recent call last):
2024-11-16T09:07:50.532636+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
2024-11-16T09:07:50.532636+00:00 app[web.1]:     await handler.callback(self.client, *args)
2024-11-16T09:07:50.532637+00:00 app[web.1]:   File "/app/plugins/inline.py", line 81, in answer
2024-11-16T09:07:50.532637+00:00 app[web.1]:     description=f'Size: {get_size(file["file_size"])}\nType: {file["file_type"]}',
2024-11-16T09:07:50.532638+00:00 app[web.1]: KeyError: 'file_type'
 Autoscroll with outputSav

**Comment by VJBots** [comment]
Solved Now
