### ISSUE TITLE
NO RESULT SHOWING 

### ISSUE THREAD

**Issue by Divytech** [VJBots/VJ-FILTER-BOT#138]
**When Result is shown in button**
```
Traceback (most recent call last):
  File "/workspace/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/workspace/.heroku/python/lib/python3.10/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/workspace/plugins/pm_filter.py", line 64, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/workspace/plugins/pm_filter.py", line 2647, in auto_filter
    btn = [
  File "/workspace/plugins/pm_filter.py", line 2650, in <listcomp>
    text=f"[{get_size(file['file_size'])}] {' '.join(filter(lambda x: not x.startswith('[') and not x.startswith('@') and not x.startswith('www.'), file['file_name'].split()))}", callback_data=f'{pre}#{file["file_id"]}'
KeyError: 'file_id'
```
**When result is set to be in text format**
```Traceback (most recent call last):
  File "/workspace/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/workspace/.heroku/python/lib/python3.10/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/workspace/plugins/pm_filter.py", line 64, in give_filter
    await auto_filter(client, message.text, message, reply_msg, ai_search)
  File "/workspace/plugins/pm_filter.py", line 2749, in auto_filter
    cap += f"<b>📁 <a href='https://telegram.me/{temp.U_NAME}?start=files_{file['file_id']}'>[{get_size(file['file_size'])}] {' '.join(filter(lambda x: not x.startswith('[') and not x.startswith('@') and not x.startswith('www.'), file['file_name'].split()))}\n\n</a></b>"
KeyError: 'file_id'```

**Comment by VJBots** [comment]
You are using old mongodb, use new mongodb and index again

**Comment by Divytech** [comment]
Are you gone mad u are telling me to use new db instead of my db which has more than 1miliion indexed files ? What is going wrong it is previously working fine and also u r not replying on telegram ?
